export const appConstants = {
    INIT_SERVICES: 'INIT_SERVICES',
    SIGN_IN: 'SIGN_IN',
    USER_AUTH: 'USER_AUTH',
    USER_SET_DETAILS: 'USER_SET_DETAILS',
    USER_SET_SIGN_IN_STATUS: 'USER_SET_SIGN_IN_STATUS'
};
